mutation ($id: UUID!, $name: String!, $surname: String!, $email: String!) {
  result: userInsert(
    user: { id: $id, name: $name, surname: $surname, email: $email }
  ) {
    id
    msg
    result: user {
      id
      lastchange
    }
  }
}
